export const sentences = [
    "El sol brilla en el cielo azul.",
    "Los pájaros cantan por la mañana.",
    "Un gato juega con una pelota.",
    "Las flores son de colores bonitos.",
    "El agua es refrescante en verano.",
    "Un perro corre en el parque verde.",
    "La luna sale en la noche estrellada.",
    "Los niños ríen y se divierten.",
    "El pastel huele delicioso en el horno.",
    "El mar se extiende a lo lejos.",
    "Los amigos se ayudan mutuamente.",
    "Un arcoíris aparece después de la lluvia.",
    "La abeja zumba alrededor de las flores.",
    "El viento sopla suavemente en el campo.",
    "Leí una nueva historia en un libro.",
    "El chocolate es un dulce muy sabroso.",
    "Los árboles dan sombra en días calurosos.",
    "Los globos vuelan alto en el cielo.",
    "La música alegra nuestros corazones.",
    "El invierno trae nieve y frío.",
    "Un coche rojo va a toda velocidad.",
    "Los zapatos nuevos son cómodos.",
    "Los colores del otoño son hermosos.",
    "Un abrazo puede hacer feliz a alguien.",
    "El río fluye tranquilo en la mañana.",
    "La risa es contagiosa.",
    "Las estrellas brillan en la noche.",
    "Un helado refresca en días calurosos.",
    "Las mariposas revolotean en el jardín.",
    "La lluvia cae suavemente sobre el suelo.",
    "El teléfono suena anunciando una llamada.",
    "Las estaciones cambian a lo largo del año.",
    "Un sombrero protege del sol.",
    "El bebé ríe al ver un juguete.",
    "Los deportes son divertidos y saludables.",
    "La montaña se ve majestuosa desde lejos.",
    "Un reloj marca las horas del día.",
    "La comida casera es deliciosa.",
    "El payaso hace reír a la gente.",
    "En el río se ven peces nadando.",
    "Un barco navega en el océano.",
    "Las hojas caen del árbol.",
    "El tren pasa por la estación a cada hora.",
    "Un cuento antes de dormir es reconfortante.",
    "El arcoíris tiene colores muy bonitos.",
    "Me gusta andar en bicicleta con mis amigos.",
    "La risa es la mejor medicina.",
    "El invierno trae consigo la Navidad.",
    "Un paraguas nos protege de la lluvia.",
    "Los zapatos cómodos son importantes.",
    "Los amigos son como tesoros en la vida."
  ];

  