export const words = [
    "montaña", "pueblo", "cine", "teatro", "arte", "pintura", "escultura", "museo", "escritura",
    "poesía", "prosa", "novela", "cuento", "revista", "periódico", "revolución", "independencia",
    "libertad", "igualdad", "derechos", "justicia", "gobierno", "política", "democracia", "monarquía",
    "constitución", "ley", "juez", "juicio", "abogado", "crimen", "castigo", "prisión", "sentencia",
    "inocente", "culpable", "testigo", "evidencia", "verdad", "mentira", "engaño", "sinceridad",
    "confianza", "traición", "relación", "matrimonio", "divorcio", "soltero", "soltera", "novio",
    "novia", "pasión", "celos", "envidia", "romance", "competencia", "victoria", "derrota", "logro",
    "meta", "sueño", "realidad", "imaginación", "inspiración", "originalidad", "copia", "cambio",
    "transformación", "evolución", "innovación", "tradición", "costumbre", "experiencia", "memoria",
    "pasado", "presente", "futuro", "tiempo", "espacio", "universo", "estrella", "planeta", "luna",
    "sol", "galaxia", "nebulosa", "cometa", "meteorito", "astronomía", "espacio", "exploración",
    "descubrimiento", "ciencia", "investigación", "experimento", "teoría", "hipótesis", "ética",
    "moral", "valores", "principios", "virtud", "vicio", "respeto", "tolerancia", "discriminación",
    "diversidad", "minoría", "mayoría", "relación", "interacción", "comunicación", "lenguaje",
    "palabra", "significado", "interpretación", "expresión", "escuchar", "hablar", "escribir", "leer",
    "medio", "tecnología", "innovación", "avance", "desarrollo", "progreso", "robot", "inteligencia",
    "automatización", "trabajo", "empleo", "desempleo", "educación", "aprendizaje", "conocimiento",
    "sabiduría", "maestro", "estudiante", "escuela", "universidad", "profesión", "carrera", "habilidad",
    "destreza", "talento", "música", "literatura", "física", "química", "biología",
    "matemáticas", "historia", "geografía", "filosofía", "economía", "naturaleza", "ambiente",
    "climático", "sostenibilidad", "recursos", "energía", "agua", "aire", "animal", "planta",
    "ecosistema", "biodiversidad", "extinción", "evolución", "adaptación", "genética",
    "felicidad", "tristeza", "ira", "miedo", "alegría", "sorpresa", "asombro", "calma", "ansiedad",
    "paz", "batalla", "ejército", "soldado", "arma", "diplomacia", "tratado", "negociación", "cooperación",
    "conflicto", "crisis", "desastre", "emergencia", "ayuda", "solidaridad", "caridad", "voluntario",
    "religión", "creencia", "espiritualidad", "ritual", "cielo", "infierno", "álma", "cuerpo", "mente",
    "emoción", "sentimiento", "amistad", "verbal",
    "comunicador", "comunicado", "comunicabilidad", "comunicología",
    "lengua", "idioma", "gramática", "sintaxis", "ortografía", "vocabulario", "léxico", "significado", "semántica",
    "pragmática"
];


